version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    volumes:
      - postgres_container:/var/lib/postgresql/data
      - ./Backend/bk/exportacion.sql:/docker-entrypoint-initdb.d/exportacion.sql
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: 1234
    networks:
      - practica_net
      
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_container
    environment:
      - PG_USER=david
      - PG_PASSWORD=1234
      - PG_HOST=postgres_container
      - PG_PORT=5432
      - PG_DB=emove
    volumes:
      - ./Backend:/app
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    networks:
      - practica_net

  frontend-react:
    build:
      context: ./Frontend
    container_name: frontend_react
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
    networks:
      - practica_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_USER: david
      PGADMIN_DEFAULT_EMAIL: david@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
          - practica_net

  nginx:
    image: nginx:latest
    container_name: nginx_loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend-react
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - practica_net
      
volumes:
  postgres_container:
  pgadmin-data: {}

networks:
  practica_net: {}


