version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    volumes:
      - postgres_container:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql 
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: 1234
    networks:
      - practica_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_container
    environment:
      - PG_USER=david
      - PG_PASSWORD=1234
      - PG_HOST=postgres_container
      - PG_PORT=5432
      - PG_DB=emove
    volumes:
      - ./Backend:/app
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    networks:
      - practica_net

  frontend-react:
    build:
      context: ./Frontend
    container_name: frontend_react
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
    networks:
      - practica_net

volumes:
  postgres_container:
  
networks:
  practica_net: {}
  
