# Generated by Django 5.0.1 on 2024-01-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_stations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
