# Generated by Django 5.0.1 on 2024-01-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_alter_stations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stations',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stations',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
