# Generated by Django 5.0.1 on 2024-01-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_alter_stations_latitude_alter_stations_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='stations',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
