# Generated by Django 5.0.1 on 2024-02-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0001_initial'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='end_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_slot', to='slots.slots'),
        ),
        migrations.AddField(
            model_name='rent',
            name='initial_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_slot', to='slots.slots'),
        ),
    ]
